### PR TITLE
Fixes #71 - Handle unnecessary exceptions.

### LINKED ISSUE #71: Fix collector so that erroneous duplicate records and missing URI components do not break collection
Common exceptions that can be avoided are:

`Undefined index: host` (/local/csp/collector.php on line 59)

`Error: testdb->get_record() found more than one record!` (/local/csp/collector.php on line 44)

### PR DESCRIPTION
**Pull request by andrewmadden**
* Be more forgiving when breaking apart URI's to store in DB.
* Merge duplicate rows that share the same sha1hash

### CODE REVIEW

File: collector.php [hunk 1]
```diff
@@ -40,8 +40,17 @@
     // We will be judging if CSP report is already recorded by searching over
     // the fields document-uri, blocked-uri, violated-directive, by hashing them.
     // This means that the truncated URI can be stored, while being properly deduped using the full data.
+    // The sha1hash is not always unique as there may be multiple records before the hash was properly implemented.
```
Comment (brendanheywood) [inline collector.php]: Why not move this into an upgrade script and keep the logic here simpler?

Comment (andrewmadden) [reply collector.php]: I thought about it. Main reason was that I saw some funny data in a live site that looked like the plugin may still be making duplicate records somewhere due to records with matching hashes and timestamps but non-1 failcounts.

I figured this way it will continue to repair the DB keeping the data intact if there is a bug somewhere else, otherwise it's only adding an extra if statement to the computation time.

**Comment by andrewmadden** [comment]
* Wrapped the deduplication in an ad-hoc task that gets every duplicated record.
* Added the ad-hoc task to the upgrade script.

File: collector.php [hunk 2]
```diff
@@ -55,9 +55,9 @@
             echo "OK\n";
         } else {
             // Set the 'blockeddomain' and 'blockedurlpath' values.
-            $parsedurl = parse_url($blockeduri);
-            $blockeddomain = $parsedurl['host'];
-            $blockedurlpath = $parsedurl['path'];
+            $parsedurl = new \moodle_url($blockeduri);
```
Comment (Peterburnett) [inline collector.php]: Can we always safely assume this is a moodle URI?  It feels correct to have some level of parsing and sanity checking in place here, as previous

File: classes/helper.php [hunk 3]
```diff
@@ -131,4 +131,50 @@ public static function enable_notifications() : string {
...
+            throw new \moodle_exception('norecordsfound', 'local_csp');
+        }
+
+        // If only 1 record provided, just return it.
+        if (count($records) === 1) {
+            return reset($records);
+        }
+
+        // Order records by DESC failcounter, as highest fail counter will be the base record.
+        usort($records, function($a, $b) {
```
Comment (Peterburnett) [inline classes/helper.php]: Does this actually matter? they should be identical. The only thing I can think of is timestamps, otherwise we can be a little faster if the sort isnt needed

File: classes/helper.php [hunk 4]
```diff
@@ -131,4 +131,50 @@ public static function enable_notifications() : string {
...
+        }
+        $baserecord->timeupdated = time();
+
+        $idstodelete = array_map(function($record) {
+            return $record->id;
+        }, $records);
+
+        // Remove duplicates, and update base record.
+        $transaction = $DB->start_delegated_transaction();
+        $DB->delete_records_list('local_csp', 'id', $idstodelete);
```
Comment (Peterburnett) [inline classes/helper.php]: This might need an explain plan to confirm, but would it be faster to just delete all records with the sha1hash then just insert a new record. My thinking is there is 1 less check per record, and there are tons of records, so it saves on potentially pushing a massive list through.

File: classes/helper.php (hunk 3 above)
Comment (andrewmadden) [reply classes/helper.php]: Yeah timestamps were why I did (and being unfamiliar with significance of different data). If you don't think which record ultimately is kept then I can remove this.

File: collector.php (hunk 2 above)
Comment (andrewmadden) [reply collector.php]: I found out in the SEB work that despite it being called moodle_url, it actually just does a lot of useful parsing to any url you pass it. We use it to break apart safe exam browser urls. 

Reason I used it here is that if a 'host' isn't found in the URI, it won't throw an error and just provide back the default which is an empty string. Previously it wouldn't save a record as an exeption would be thrown

File: classes/helper.php (hunk 4 above)
Comment (andrewmadden) [reply classes/helper.php]: Maybe. It'll take a bit of effort to test this with scale though. I can just do it as your suggestion to avoid having to set up the data. I can't imagine it being slower.

File: classes/helper.php (hunk 3 above)
Comment (andrewmadden) [reply classes/helper.php:154]: One thing that becomes really annoying is testing if it's not sorted, though.

**Comment by andrewmadden** [comment]
Removed the sorting based on failcounter. 

Merging now deletes all records matching hash, then inserts a fresh record, rather than using a list of ids.

File: classes/helper.php [hunk 5]
```diff
@@ -131,4 +131,46 @@ public static function enable_notifications() : string {
...
+        $baserecord = array_shift($records);
+        foreach ($records as $record) {
+            if ($baserecord->sha1hash != $record->sha1hash) {
+                throw new \moodle_exception('nonduplicaterecords', 'local_csp');
+            }
+            $baserecord->failcounter += $record->failcounter;
+        }
+        $baserecord->timeupdated = time();
+
+        $idstodelete = array_map(function($record) {
```
Comment (Peterburnett) [inline classes/helper.php]: THis can be killed now

Comment (andrewmadden) [reply classes/helper.php]: deleted
